package errortest;

public class errortest1 {
	public static void main(String args[]){
		int a, b;
		a = 50;
		b = 0;
		
		try{
			System.out.println("계산결과는 ");
			divide(a, b);
			System.out.println("입니다");
		} catch (Exception e) {
			System.out.println("오류발생 " + e.getLocalizedMessage());
		}
		
	}

	static void divide(int a, int b){
		System.out.println(a/b);
	}


}


